# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: two_pc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctwo_pc.proto\x12\x06two_pc\"P\n\x0bVoteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\x11\n\toperation\x18\x03 \x01(\t\"K\n\x0cVoteResponse\x12\x12\n\ncan_commit\x18\x01 \x01(\x08\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t2G\n\x0bTwoPCVoting\x12\x38\n\x0bRequestVote\x12\x13.two_pc.VoteRequest\x1a\x14.two_pc.VoteResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'two_pc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VOTEREQUEST._serialized_start=24
  _VOTEREQUEST._serialized_end=104
  _VOTERESPONSE._serialized_start=106
  _VOTERESPONSE._serialized_end=181
  _TWOPCVOTING._serialized_start=183
  _TWOPCVOTING._serialized_end=254
# @@protoc_insertion_point(module_scope)
