# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: raft.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"8\n\x08LogEntry\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\r\n\x05index\x18\x02 \x01(\x04\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\t\"\xe6\x01\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x16\n\x0eprev_log_index\x18\x03 \x01(\x04\x12\x15\n\rprev_log_term\x18\x04 \x01(\x04\x12\x1f\n\x07\x65ntries\x18\x05 \x03(\x0b\x32\x0e.raft.LogEntry\x12\x15\n\rleader_commit\x18\x06 \x01(\x04\x12\x11\n\theartbeat\x18\x07 \x01(\x08\x12\x16\n\x0eleader_address\x18\x08 \x01(\t\x12\x1b\n\x13leader_http_address\x18\t \x01(\t\"t\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x13\n\x0bmatch_index\x18\x03 \x01(\x04\x12\x16\n\x0elast_log_index\x18\x04 \x01(\x04\x12\x0f\n\x07message\x18\x05 \x01(\t\"g\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\t\x12\x16\n\x0elast_log_index\x18\x03 \x01(\x04\x12\x15\n\rlast_log_term\x18\x04 \x01(\x04\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x04\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\":\n\x14\x43lientCommandRequest\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\"\x93\x01\n\x15\x43lientCommandResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x11\n\tleader_id\x18\x02 \x01(\t\x12\x1b\n\x13leader_http_address\x18\x03 \x01(\t\x12\x11\n\tlog_index\x18\x04 \x01(\x04\x12\x14\n\x0c\x63ommit_index\x18\x05 \x01(\x04\x12\x0f\n\x07message\x18\x06 \x01(\t2\xe5\x01\n\x0bRaftService\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12\x42\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\x12H\n\rClientCommand\x12\x1a.raft.ClientCommandRequest\x1a\x1b.raft.ClientCommandResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGENTRY._serialized_start=20
  _LOGENTRY._serialized_end=76
  _APPENDENTRIESREQUEST._serialized_start=79
  _APPENDENTRIESREQUEST._serialized_end=309
  _APPENDENTRIESRESPONSE._serialized_start=311
  _APPENDENTRIESRESPONSE._serialized_end=427
  _REQUESTVOTEREQUEST._serialized_start=429
  _REQUESTVOTEREQUEST._serialized_end=532
  _REQUESTVOTERESPONSE._serialized_start=534
  _REQUESTVOTERESPONSE._serialized_end=591
  _CLIENTCOMMANDREQUEST._serialized_start=593
  _CLIENTCOMMANDREQUEST._serialized_end=651
  _CLIENTCOMMANDRESPONSE._serialized_start=654
  _CLIENTCOMMANDRESPONSE._serialized_end=801
  _RAFTSERVICE._serialized_start=804
  _RAFTSERVICE._serialized_end=1033
# @@protoc_insertion_point(module_scope)
