# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: two_pc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ctwo_pc.proto\x12\x06two_pc\"d\n\x12TransactionPayload\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\x12\x11\n\toperation\x18\x04 \x01(\t\"V\n\x0bVoteRequest\x12\x16\n\x0eparticipant_id\x18\x01 \x01(\t\x12/\n\x0btransaction\x18\x02 \x01(\x0b\x32\x1a.two_pc.TransactionPayload\"\\\n\x0cVoteResponse\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\x0c\n\x04vote\x18\x03 \x01(\x08\x12\x0e\n\x06reason\x18\x04 \x01(\t\"Q\n\x0f\x44\x65\x63isionRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x0e\n\x06\x63ommit\x18\x02 \x01(\x08\x12\x16\n\x0e\x63oordinator_id\x18\x03 \x01(\t\"W\n\x03\x41\x63k\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x16\n\x0eparticipant_id\x18\x02 \x01(\t\x12\x0f\n\x07\x61pplied\x18\x03 \x01(\x08\x12\x0f\n\x07message\x18\x04 \x01(\t2E\n\rVotingService\x12\x34\n\x07Prepare\x12\x13.two_pc.VoteRequest\x1a\x14.two_pc.VoteResponse2H\n\x0f\x44\x65\x63isionService\x12\x35\n\rCommitOrAbort\x12\x17.two_pc.DecisionRequest\x1a\x0b.two_pc.Ackb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'two_pc_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTIONPAYLOAD._serialized_start=24
  _TRANSACTIONPAYLOAD._serialized_end=124
  _VOTEREQUEST._serialized_start=126
  _VOTEREQUEST._serialized_end=212
  _VOTERESPONSE._serialized_start=214
  _VOTERESPONSE._serialized_end=306
  _DECISIONREQUEST._serialized_start=308
  _DECISIONREQUEST._serialized_end=389
  _ACK._serialized_start=391
  _ACK._serialized_end=478
  _VOTINGSERVICE._serialized_start=480
  _VOTINGSERVICE._serialized_end=549
  _DECISIONSERVICE._serialized_start=551
  _DECISIONSERVICE._serialized_end=623
# @@protoc_insertion_point(module_scope)
