# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import two_pc_pb2 as two__pc__pb2


class VotingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Prepare = channel.unary_unary(
                '/two_pc.VotingService/Prepare',
                request_serializer=two__pc__pb2.VoteRequest.SerializeToString,
                response_deserializer=two__pc__pb2.VoteResponse.FromString,
                )


class VotingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Prepare(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VotingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.Prepare,
                    request_deserializer=two__pc__pb2.VoteRequest.FromString,
                    response_serializer=two__pc__pb2.VoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'two_pc.VotingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VotingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/two_pc.VotingService/Prepare',
            two__pc__pb2.VoteRequest.SerializeToString,
            two__pc__pb2.VoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class DecisionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CommitOrAbort = channel.unary_unary(
                '/two_pc.DecisionService/CommitOrAbort',
                request_serializer=two__pc__pb2.DecisionRequest.SerializeToString,
                response_deserializer=two__pc__pb2.Ack.FromString,
                )


class DecisionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CommitOrAbort(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CommitOrAbort': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitOrAbort,
                    request_deserializer=two__pc__pb2.DecisionRequest.FromString,
                    response_serializer=two__pc__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'two_pc.DecisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DecisionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CommitOrAbort(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/two_pc.DecisionService/CommitOrAbort',
            two__pc__pb2.DecisionRequest.SerializeToString,
            two__pc__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
